name: Build & Test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Get Environment & Secrets (Development)
        if: github.ref != 'refs/heads/master' && !contains(github.ref, '/rl-')
        run: |
          echo "buildConfiguration=Debug" >> $GITHUB_ENV
          echo "azureAppInsightsConnectionString=${{ secrets.AZURE_APP_INSIGHTS_CONNECTION_STRING_DEV }}" >> $GITHUB_ENV
      - name: Get Environment & Secrets (Production)
        if: github.ref == 'refs/heads/master' || contains(github.ref, '/rl-')
        run: |
          echo "buildConfiguration=Release" >> $GITHUB_ENV
          echo "azureAppInsightsConnectionString=${{ secrets.AZURE_APP_INSIGHTS_CONNECTION_STRING_PROD }}" >> $GITHUB_ENV
      - name: Apply Secrets
        working-directory: src/BWHazel.Portfolio.Web/wwwroot
        run: |
          jq '.ConnectionStrings.AzureApplicationInsights = "${{ env.azureAppInsightsConnectionString }}"' appsettings.json > appsettings.temp.json
          mv appsettings.temp.json appsettings.json
      - name: Build
        working-directory: src
        run: dotnet build --configuration ${{ env.buildConfiguration }}
      - name: Test
        working-directory: src
        run: dotnet test --no-build
      - name: Package
        working-directory: src/BWHazel.Portfolio.Web
        run: dotnet publish --configuration ${{ env.buildConfiguration }} -o ../../dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bwhazel-portfolio-web-site
          path: dist